model_list:
  - model_name: haiku
    litellm_params:
      model: openai/haiku
      api_base: http://vllm_haiku:8001/v1
      api_key: "not-needed"

  - model_name: sonnet
    litellm_params:
      model: openai/sonnet
      api_base: http://vllm_sonnet:8002/v1
      api_key: "not-needed"

  - model_name: opus
    litellm_params:
      model: openai/opus
      api_base: http://vllm_opus:8003/v1
      api_key: "not-needed"

router_settings:
  routing_strategy: simple-shuffle

general_settings:
  master_key: "CHANGE_ME" # optional auth for the router
